services:
  knowledge:
    image: codeclarityce/service-knowledge:0.0.1-alpha
    restart: always
    env_file:
      - .env.codeclarity
      - .env.knowledge
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
        reservations:
          cpus: '1'
          memory: 2G